### ISSUE TITLE
안녕하세요 부경대학교 컴공과 학생인데요, 혹시 연락할 수 있을까요?

### ISSUE THREAD

**Issue by hogyun-kim** [domokim2/forever.github#1]
안녕하세요, 부경대학교 컴공과 학생인데요
ACM-ICPC 대회 관련으로 연락을 하고 싶은데
hogyoon.kim@gmail.com 으로 연락해주실 수 있을까요?

**Comment by domokim2** [comment]
연락 드렸습니다
